# Generated by Django 3.2.12 on 2022-03-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220315_2248'),
        ('menus', '0006_alter_menu_is_public'),
        ('log_and_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menus',
            field=models.ManyToManyField(related_name='users', to='menus.Menu'),
        ),
        migrations.AddField(
            model_name='user',
            name='recipes',
            field=models.ManyToManyField(related_name='users', to='recipes.Recipe'),
        ),
    ]
