# Generated by Django 3.2.12 on 2022-03-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20220315_2248'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='days',
            field=models.ManyToManyField(related_name='days', to='menus.Day'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_types',
            field=models.ManyToManyField(related_name='recipe_types', to='recipes.RecipeType'),
        ),
    ]
