# Generated by Django 3.2.12 on 2022-03-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_day_menu'),
        ('recipes', '0002_auto_20220315_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='days',
            field=models.ManyToManyField(related_name='recipes', to='menus.Day'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_types',
            field=models.ManyToManyField(related_name='recipes', to='recipes.RecipeType'),
        ),
    ]
