# Generated by Django 3.2.12 on 2022-03-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=45)),
                ('meals', models.ManyToManyField(related_name='recipes', to='recipes.Recipe')),
            ],
        ),
    ]
