# Generated by Django 3.2.12 on 2022-03-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_day_menu'),
        ('recipes', '0006_auto_20220321_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='days',
            field=models.ManyToManyField(related_name='meals', to='menus.Day'),
        ),
    ]
