# Generated by Django 3.2.12 on 2022-03-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_mealtype_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtype',
            name='days',
        ),
    ]
