# Generated by Django 3.2.12 on 2022-03-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_day_menu'),
        ('recipes', '0008_remove_mealtype_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='menus',
            field=models.ManyToManyField(related_name='recipes', to='menus.Menu'),
        ),
    ]
