# Generated by Django 3.2.12 on 2022-03-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='tags',
            field=models.ManyToManyField(related_name='days', to='menus.Tag'),
        ),
    ]
