# Generated by Django 3.2.12 on 2022-03-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20220319_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
