# Generated by Django 3.2.12 on 2022-03-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menu_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='public',
            new_name='is_public',
        ),
    ]
