# Generated by Django 3.2.12 on 2022-03-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_rename_public_menu_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_public',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
